### ISSUE TITLE
superCtor.prototype - Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by trickpattyFH20** [emersion/tls-browserify#3]
I would LOVE to use this module but I am having trouble implementing it with a browserify bundle.
I am getting an error from the node-forge dependency when I try to include this in browserify:

`var tls = require('tls-browserify');`
`exports.tls = tls;`

gives me the error "Cannot read property 'prototype' of undefined"
which seems to come from line 15560 of jscs-browser.js of the node-forge module...

are there any examples of how tls-browserify has been implemented in a browserify bundle?

**Comment by trickpattyFH20** [comment]
apparently the issue of superCtor being undefined comes from calling .inhert incorrectly. 

in this case, tls-browserify was trying to call require('net') in browserify, which is prevented and then runs .inhert() with net as a param.

**I resolved the issue by replacing `net` with `net-browserify`**

**Comment by emersion** [comment]
You can change the `builtins` option of browserify. See https://github.com/emersion/node-client-vm/blob/master/src/lib/api/index.js#L54 and https://github.com/emersion/node-client-vm/blob/master/src/lib/api/builtins.js to see how to do this.
